import { Rows3,Search } from 'lucide-react';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { allowedMccIds } from '@/lib/data-access';
import { formatCustomerId,formatMoney,formatNumber } from '@/lib/google-ads-format';
import { prisma } from '@/lib/prisma';
import { dateLocale,tr } from '@/lib/i18n';
import { getAppLocale } from '@/lib/i18n-server';
import { MccOwnershipBadge } from '../mcc-ownership-badge';
import { ShareAccountButton } from '../share-account-button';

type Query={q?:string;mcc?:string;status?:string;currency?:string};
export default async function AccountsPage({searchParams}:{searchParams:Promise<Query>}){
  const user=await getCurrentUser();if(!user)redirect('/login?returnTo=/google-ads/accounts');const query=await searchParams;const locale=await getAppLocale();const numberLocale=dateLocale(locale);const allowed=await allowedMccIds(user);
  const where={AND:[allowed===null?{}:{mccId:{in:allowed}},query.mcc?{mccId:query.mcc}:{},query.status&&query.status!=='ALL'?{status:query.status as 'ENABLED'|'SUSPENDED'|'CANCELED'|'CLOSED'|'UNKNOWN'}:{},query.currency?{currency:query.currency}:{},query.q?{OR:[{name:{contains:query.q,mode:'insensitive' as const}},{customerId:{contains:query.q.replace(/\D/g,'')}},{mcc:{name:{contains:query.q,mode:'insensitive' as const}}}]}:{}]};
  const accounts=await prisma.customerAccount.findMany({where,include:{mcc:{select:{id:true,name:true,customerId:true}}},orderBy:{name:'asc'},take:500});
  const totals=accounts.length?await prisma.dailyMetric.groupBy({by:['customerAccountId'],where:{customerAccountId:{in:accounts.map(item=>item.id)}},_sum:{cost:true,clicks:true,impressions:true,conversions:true}}):[];const metricMap=new Map(totals.map(item=>[item.customerAccountId,item._sum]));
  const filters=await prisma.customerAccount.findMany({where:allowed===null?{}:{mccId:{in:allowed}},select:{currency:true,mcc:{select:{id:true,name:true}}},distinct:['currency']});
  const mccOptions=[...new Map(filters.map(item=>[item.mcc.id,item.mcc])).values()];const currencies=[...new Set(filters.map(item=>item.currency).filter(Boolean))] as string[];
  return <><div className="ga-page-head"><div><p>GOOGLE ADS</p><h1>{tr(locale,'Tài khoản khách hàng','Customer accounts')}</h1><span>{tr(locale,'Tài khoản thật được phát hiện qua Google OAuth và customer_client.','Real accounts discovered through Google OAuth and customer_client.')}</span></div></div><form className="ga-filters"><label><Search size={14}/><input name="q" defaultValue={query.q} placeholder={tr(locale,'Customer ID, tên tài khoản, MCC','Customer ID, account name, MCC')}/></label><select name="mcc" defaultValue={query.mcc||''}><option value="">{tr(locale,'Tất cả MCC','All MCCs')}</option>{mccOptions.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><select name="status" defaultValue={query.status||'ALL'}><option value="ALL">{tr(locale,'Tất cả trạng thái','All statuses')}</option>{['ENABLED','SUSPENDED','CANCELED','CLOSED','UNKNOWN'].map(value=><option key={value}>{value}</option>)}</select><select name="currency" defaultValue={query.currency||''}><option value="">{tr(locale,'Tất cả tiền tệ','All currencies')}</option>{currencies.map(value=><option key={value}>{value}</option>)}</select><button>{tr(locale,'Tìm kiếm','Search')}</button></form>
    {accounts.length===0?<section className="ga-empty"><Rows3 size={28}/><h2>{tr(locale,'Không có tài khoản phù hợp','No matching accounts')}</h2><p>{tr(locale,'Hãy kết nối/làm mới Google Ads hoặc thay đổi bộ lọc.','Connect or refresh Google Ads, or change the filters.')}</p></section>:<section className="ga-panel ga-table-panel"><div className="ga-table-wrap"><table className="ga-table"><thead><tr><th>{tr(locale,'Tên tài khoản','Account name')}</th><th>Customer ID</th><th>MCC</th><th>{tr(locale,'MCC quản lý tài khoản','MCC management access')}</th><th>{tr(locale,'Trạng thái','Status')}</th><th>{tr(locale,'Tiền tệ','Currency')}</th><th>{tr(locale,'Múi giờ','Timezone')}</th><th>{tr(locale,'Chi tiêu','Spend')}</th><th>{tr(locale,'Lượt nhấp','Clicks')}</th><th>{tr(locale,'Lượt hiển thị','Impressions')}</th><th>{tr(locale,'Lượt chuyển đổi','Conversions')}</th>{user.role==='ADMIN'&&<th>{tr(locale,'Chia sẻ','Share')}</th>}</tr></thead><tbody>{accounts.map(account=>{const metric=metricMap.get(account.id);return <tr key={account.id}><td><a href={`/google-ads/accounts/${account.id}`}>{account.name}</a></td><td>{formatCustomerId(account.customerId)}</td><td>{account.mcc.name}</td><td><MccOwnershipBadge hasOwnership={account.mccHasOwnership} errorCode={account.mccOwnershipErrorCode} locale={locale}/></td><td><span className={`ga-status ${account.status==='ENABLED'?'connected':'reauth_required'}`}>{account.status}</span></td><td>{account.currency||'—'}</td><td>{account.timezone||'—'}</td><td>{formatMoney(Number(metric?.cost||0),account.currency||'VND',numberLocale)}</td><td>{formatNumber(metric?.clicks||BigInt(0),numberLocale)}</td><td>{formatNumber(metric?.impressions||BigInt(0),numberLocale)}</td><td>{formatNumber(Number(metric?.conversions||0),numberLocale)}</td>{user.role==='ADMIN'&&<td><ShareAccountButton targetType="ACCOUNT" targetId={account.id} targetName={account.name} customerId={formatCustomerId(account.customerId)}/></td>}</tr>})}</tbody></table></div></section>}
  </>
}
