'use client';

import { useEffect,useState } from 'react';
import { ArrowLeft,KeyRound,LogOut,ShieldCheck,UserRound } from 'lucide-react';
import type { SessionUser } from '@/lib/session';

type Profile={id:string;name:string|null;email:string;role:string;status:string;lastLoginAt:string|null;databaseConfigured:boolean};
export function ProfileClient({user}:{user:SessionUser}){
  const[profile,setProfile]=useState<Profile|null>(null);const[currentPassword,setCurrentPassword]=useState('');const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');const[saving,setSaving]=useState(false);
  useEffect(()=>{let cancelled=false;fetch('/api/profile').then(async response=>await response.json() as {data?:Profile}).then(payload=>{if(!cancelled&&payload.data)setProfile(payload.data)});return()=>{cancelled=true}},[]);
  async function changePassword(event:React.FormEvent){event.preventDefault();setError('');setMessage('');if(newPassword!==confirmPassword){setError('Xác nhận mật khẩu không khớp.');return}setSaving(true);const response=await fetch('/api/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});const payload=await response.json() as {error?:{message?:string}};if(!response.ok){setError(payload.error?.message||'Không thể đổi mật khẩu.');setSaving(false);return}await fetch('/api/auth/logout-all',{method:'POST'});window.location.assign('/login');}
  async function logoutAll(){setSaving(true);await fetch('/api/auth/logout-all',{method:'POST'});window.location.assign('/login')}
  return <main className="profile-shell"><header className="profile-top"><a href="/dashboard"><ArrowLeft size={16}/> Dashboard</a><div className="login-brand"><span className="brand-mark">A</span><span>Ads Manager <b>Pro</b></span></div></header><section className="profile-grid"><article className="panel profile-summary"><span className="profile-avatar"><UserRound size={25}/></span><h1>{profile?.name||user.name}</h1><p>{profile?.email||user.email}</p><div><span><ShieldCheck size={14}/> Vai trò</span><strong>{profile?.role||user.role}</strong></div><div><span>Trạng thái</span><strong className="profile-active">{profile?.status||'ACTIVE'}</strong></div><div><span>Đăng nhập gần nhất</span><strong>{profile?.lastLoginAt?new Date(profile.lastLoginAt).toLocaleString('vi-VN'):'Phiên hiện tại'}</strong></div></article><article className="panel password-card"><span className="invite-icon"><KeyRound size={19}/></span><h2>Đổi mật khẩu</h2><p>Đổi mật khẩu sẽ đăng xuất tất cả phiên đang hoạt động.</p>{!profile?.databaseConfigured&&<div className="database-notice">Cần cấu hình DATABASE_URL để đổi mật khẩu.</div>}<form onSubmit={changePassword}><label>Mật khẩu hiện tại<input type="password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required/></label><label>Mật khẩu mới<input type="password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} minLength={10} maxLength={128} required/></label><label>Xác nhận mật khẩu<input type="password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} minLength={10} maxLength={128} required/></label>{error&&<div className="team-error">{error}</div>}{message&&<div className="login-success">{message}</div>}<button disabled={saving||profile?.databaseConfigured===false}>{saving?'Đang xử lý...':'Đổi mật khẩu'}</button></form><button className="logout-all" onClick={logoutAll} disabled={saving}><LogOut size={15}/> Đăng xuất tất cả phiên</button></article></section></main>
}
