'use client';

import { useEffect,useState } from 'react';
import { ArrowLeft,KeyRound,LogOut,ShieldCheck,UserRound } from 'lucide-react';
import { dateLocale, tr } from '@/lib/i18n';
import type { SessionUser } from '@/lib/session';
import { BrandLogo } from '../brand-logo';
import { AppLanguageSwitcher } from '../language-switcher';
import { useAppLocale } from '../locale-provider';

type Profile={id:string;name:string|null;email:string;role:string;status:string;lastLoginAt:string|null;databaseConfigured:boolean};
export function ProfileClient({user}:{user:SessionUser}){
  const locale=useAppLocale();
  const[profile,setProfile]=useState<Profile|null>(null);const[currentPassword,setCurrentPassword]=useState('');const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');const[saving,setSaving]=useState(false);
  useEffect(()=>{let cancelled=false;fetch('/api/profile').then(async response=>await response.json() as {data?:Profile}).then(payload=>{if(!cancelled&&payload.data)setProfile(payload.data)});return()=>{cancelled=true}},[]);
  async function changePassword(event:React.FormEvent){event.preventDefault();setError('');setMessage('');if(newPassword!==confirmPassword){setError(tr(locale,'Xác nhận mật khẩu không khớp.','Password confirmation does not match.'));return}setSaving(true);const response=await fetch('/api/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});const payload=await response.json() as {error?:{message?:string}};if(!response.ok){setError(payload.error?.message||tr(locale,'Không thể đổi mật khẩu.','Unable to change password.'));setSaving(false);return}await fetch('/api/auth/logout-all',{method:'POST'});window.location.assign('/login');}
  async function logoutAll(){setSaving(true);await fetch('/api/auth/logout-all',{method:'POST'});window.location.assign('/login')}
  return <main className="profile-shell"><header className="profile-top"><a href="/dashboard"><ArrowLeft size={16}/> {tr(locale,'Tổng quan','Dashboard')}</a><div className="login-brand"><BrandLogo decorative /><span>David Agency MCC Manager</span></div><AppLanguageSwitcher/></header><section className="profile-grid"><article className="panel profile-summary"><span className="profile-avatar"><UserRound size={25}/></span><h1>{profile?.name||user.name}</h1><p>{profile?.email||user.email}</p><div><span><ShieldCheck size={14}/> {tr(locale,'Vai trò','Role')}</span><strong>{profile?.role||user.role}</strong></div><div><span>{tr(locale,'Trạng thái','Status')}</span><strong className="profile-active">{profile?.status||'ACTIVE'}</strong></div><div><span>{tr(locale,'Đăng nhập gần nhất','Last sign-in')}</span><strong>{profile?.lastLoginAt?new Date(profile.lastLoginAt).toLocaleString(dateLocale(locale)):tr(locale,'Phiên hiện tại','Current session')}</strong></div></article><article className="panel password-card"><span className="invite-icon"><KeyRound size={19}/></span><h2>{tr(locale,'Đổi mật khẩu','Change password')}</h2><p>{tr(locale,'Đổi mật khẩu sẽ đăng xuất tất cả phiên đang hoạt động.','Changing your password signs out all active sessions.')}</p>{!profile?.databaseConfigured&&<div className="database-notice">{tr(locale,'Cần cấu hình DATABASE_URL để đổi mật khẩu.','DATABASE_URL is required to change the password.')}</div>}<form onSubmit={changePassword}><label>{tr(locale,'Mật khẩu hiện tại','Current password')}<input type="password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required/></label><label>{tr(locale,'Mật khẩu mới','New password')}<input type="password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} minLength={10} maxLength={128} required/></label><label>{tr(locale,'Xác nhận mật khẩu','Confirm password')}<input type="password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} minLength={10} maxLength={128} required/></label>{error&&<div className="team-error">{error}</div>}{message&&<div className="login-success">{message}</div>}<button disabled={saving||profile?.databaseConfigured===false}>{saving?tr(locale,'Đang xử lý...','Processing...'):tr(locale,'Đổi mật khẩu','Change password')}</button></form><button className="logout-all" onClick={logoutAll} disabled={saving}><LogOut size={15}/> {tr(locale,'Đăng xuất tất cả phiên','Sign out all sessions')}</button></article></section></main>
}
