import type { AppRole } from './session';

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD', VIEW_MCC: 'VIEW_MCC', VIEW_ACCOUNT: 'VIEW_ACCOUNT', VIEW_CAMPAIGN: 'VIEW_CAMPAIGN', VIEW_ANALYTICS: 'VIEW_ANALYTICS', VIEW_SYNC_JOBS: 'VIEW_SYNC_JOBS', VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS', EXPORT_DATA: 'EXPORT_DATA',
  CREATE_MCC: 'CREATE_MCC', DELETE_MCC: 'DELETE_MCC', CONNECT_MCC: 'CONNECT_MCC', DISCONNECT_MCC: 'DISCONNECT_MCC', SYNC_DATA: 'SYNC_DATA', UPDATE_CAMPAIGN: 'UPDATE_CAMPAIGN', PAUSE_CAMPAIGN: 'PAUSE_CAMPAIGN', ENABLE_CAMPAIGN: 'ENABLE_CAMPAIGN', UPDATE_BUDGET: 'UPDATE_BUDGET',
  MANAGE_USERS: 'MANAGE_USERS', MANAGE_SETTINGS: 'MANAGE_SETTINGS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
const ALL_PERMISSIONS = Object.values(PERMISSIONS);
const STAFF_READ_PERMISSIONS: Permission[] = [PERMISSIONS.VIEW_DASHBOARD,PERMISSIONS.VIEW_MCC,PERMISSIONS.VIEW_ACCOUNT,PERMISSIONS.VIEW_CAMPAIGN,PERMISSIONS.VIEW_ANALYTICS,PERMISSIONS.VIEW_SYNC_JOBS,PERMISSIONS.VIEW_AUDIT_LOGS];

export function permissionsFor(role: AppRole): Permission[] {
  if (role === 'ADMIN') return ALL_PERMISSIONS;
  return process.env.STAFF_EXPORT_ENABLED === 'false' ? STAFF_READ_PERMISSIONS : [...STAFF_READ_PERMISSIONS,PERMISSIONS.EXPORT_DATA];
}

export function hasPermission(role: AppRole, permission: Permission) {
  return permissionsFor(role).includes(permission);
}
