import { BarChart3 } from 'lucide-react';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { allowedMccIds } from '@/lib/data-access';
import { formatMoney,formatNumber } from '@/lib/google-ads-format';
import { prisma } from '@/lib/prisma';
import { dateLocale,tr } from '@/lib/i18n';
import { getAppLocale } from '@/lib/i18n-server';

export default async function AnalyticsPage(){const user=await getCurrentUser();if(!user)redirect('/login?returnTo=/google-ads/analytics');const locale=await getAppLocale();const numberLocale=dateLocale(locale);const allowed=await allowedMccIds(user);const where={customerAccount:{mcc:allowed===null?{}:{id:{in:allowed}}}};const[totals,days]=await Promise.all([prisma.dailyMetric.aggregate({where,_sum:{cost:true,clicks:true,impressions:true,conversions:true}}),prisma.dailyMetric.groupBy({by:['date'],where,_sum:{cost:true,clicks:true,impressions:true,conversions:true},orderBy:{date:'desc'},take:30})]);return <><div className="ga-page-head"><div><p>GOOGLE ADS</p><h1>{tr(locale,'Phân tích','Analytics')}</h1><span>{tr(locale,'30 ngày dữ liệu chỉ số đã đồng bộ từ Google Ads API.','Thirty days of metrics synchronized from the Google Ads API.')}</span></div></div><div className="ga-kpis"><article><BarChart3 size={18}/><span>{tr(locale,'Chi tiêu','Spend')}</span><strong>{formatMoney(Number(totals._sum.cost||0),'VND',numberLocale)}</strong></article><article><BarChart3 size={18}/><span>{tr(locale,'Lượt nhấp','Clicks')}</span><strong>{formatNumber(totals._sum.clicks||BigInt(0),numberLocale)}</strong></article><article><BarChart3 size={18}/><span>{tr(locale,'Lượt hiển thị','Impressions')}</span><strong>{formatNumber(totals._sum.impressions||BigInt(0),numberLocale)}</strong></article><article><BarChart3 size={18}/><span>{tr(locale,'Lượt chuyển đổi','Conversions')}</span><strong>{formatNumber(Number(totals._sum.conversions||0),numberLocale)}</strong></article></div>{days.length===0?<section className="ga-empty"><BarChart3 size={28}/><h2>{tr(locale,'Chưa có chỉ số','No metrics available')}</h2><p>{tr(locale,'Mở tài khoản và bấm Làm mới để đồng bộ dữ liệu thật.','Open an account and select Refresh to synchronize real data.')}</p></section>:<section className="ga-panel ga-table-panel"><div className="ga-table-wrap"><table className="ga-table"><thead><tr><th>{tr(locale,'Ngày','Date')}</th><th>{tr(locale,'Chi tiêu','Spend')}</th><th>{tr(locale,'Lượt nhấp','Clicks')}</th><th>{tr(locale,'Lượt hiển thị','Impressions')}</th><th>{tr(locale,'Lượt chuyển đổi','Conversions')}</th></tr></thead><tbody>{days.map(day=><tr key={day.date.toISOString()}><td>{day.date.toLocaleDateString(numberLocale)}</td><td>{formatMoney(Number(day._sum.cost||0),'VND',numberLocale)}</td><td>{formatNumber(day._sum.clicks||BigInt(0),numberLocale)}</td><td>{formatNumber(day._sum.impressions||BigInt(0),numberLocale)}</td><td>{formatNumber(Number(day._sum.conversions||0),numberLocale)}</td></tr>)}</tbody></table></div></section>}</>}
