'use client';
import {AlertTriangle,Bug,CheckCircle2,RefreshCw,XCircle} from 'lucide-react';
import {useState} from 'react';
import {formatCustomerId} from '@/lib/google-ads-format';
import { tr } from '@/lib/i18n';
import { useAppLocale } from '@/app/locale-provider';

type DiagnosticError={code:string;type:string;message:string;requestId:string|null;status:number;rootStatus:string|null};
type DiagnosticIssue={customerId:string;loginCustomerId:string|null;phase:'ROOT_CUSTOMER'|'MANAGER_CHILDREN';error:DiagnosticError};
type ConnectionDiagnostic={connectionId:string;googleEmail?:string;connectionStatus?:string;success:boolean;partialSuccess?:boolean;refreshToken?:{stored:boolean;encrypted:boolean;refreshSucceeded?:boolean};developerTokenAccessLevel?:string;cloudProject?:string;api?:{version:string;accessibleCustomerIds:string[];mccs:Array<{customerId:string;parentCustomerId:string|null;manager:boolean;level:number;loginCustomerId:string|null;testAccount:boolean}>;accounts:Array<{customerId:string;parentCustomerId?:string|null;parentManagerCustomerId:string;loginCustomerId:string|null;testAccount:boolean}>;issues:DiagnosticIssue[]};error?:DiagnosticError};
type DiagnosticPayload={data?:{checkedAt:string;environment:{configured:boolean;missing:string[];oauthClientId:{configured:boolean;length:number;suffix:string|null};oauthClientSecret:{configured:boolean;length:number};developerToken:{configured:boolean;length:number;fingerprint:string|null;expectedLength:number};encryptionKey:{configured:boolean;validLength:boolean};callbackUrl:string;apiVersion:string};connections:ConnectionDiagnostic[]};error?:{message?:string}};

export function DiagnosticsPanel(){
  const locale=useAppLocale();const[busy,setBusy]=useState(false);const[result,setResult]=useState<DiagnosticPayload['data']>();const[error,setError]=useState('');
  const accessLabel=(value:string|undefined)=>{if(value==='TEST')return tr(locale,'Token chỉ dùng được với tài khoản thử nghiệm, không thể truy cập Google Ads production.','The token only works with test accounts and cannot access production Google Ads.');if(value==='NOT_EXPOSED_BY_API')return tr(locale,'Google Ads API không công bố chính xác Explorer/Basic/Standard; hãy kiểm tra trong API Center.','Google Ads API does not expose the exact Explorer/Basic/Standard level; check API Center.');return value||tr(locale,'Chưa xác định','Undetermined')};
  const displayCustomerId=(value:string|null|undefined)=>value?formatCustomerId(value):tr(locale,'Bỏ trống (truy cập trực tiếp)','Omitted (direct access)');
  async function run(){setBusy(true);setError('');const response=await fetch('/api/google-ads/diagnostics',{method:'POST'});const payload=await response.json() as DiagnosticPayload;setBusy(false);if(!response.ok||!payload.data){setError(payload.error?.message||tr(locale,'Không thể chạy chẩn đoán.','Unable to run diagnostics.'));return}setResult(payload.data)}
  return <section className="ga-diagnostics ga-panel"><div className="ga-panel-head"><div><h2>{tr(locale,'Chẩn đoán Google Ads','Google Ads diagnostics')}</h2><p>{tr(locale,'Kiểm tra OAuth refresh, cấu hình backend, customer có thể truy cập, cấu trúc MCC và lỗi API nguyên bản. Không hiển thị token/secret.','Checks OAuth refresh, backend configuration, accessible customers, MCC hierarchy, and raw API errors. Tokens and secrets are never shown.')}</p></div><button className="ga-secondary" disabled={busy} onClick={()=>void run()}>{busy?<RefreshCw className="spin" size={14}/>:<Bug size={14}/>} {busy?tr(locale,'Đang kiểm tra...','Running...'):tr(locale,'Chạy chẩn đoán','Run diagnostics')}</button></div>
    {error&&<div className="ga-diagnostic-error"><XCircle size={17}/>{error}</div>}
    {result&&<div className="ga-diagnostic-body"><div className="ga-diagnostic-config"><span>API <b>{result.environment.apiVersion}</b></span><span>Client ID <b>{result.environment.oauthClientId.configured?tr(locale,'Đã cấu hình','Configured'):tr(locale,'Thiếu','Missing')}</b></span><span>Client Secret <b>{result.environment.oauthClientSecret.configured?tr(locale,'Đã cấu hình','Configured'):tr(locale,'Thiếu','Missing')}</b></span><span>Developer Token <b>{result.environment.developerToken.length}/{result.environment.developerToken.expectedLength} {tr(locale,'ký tự','chars')}</b></span><span>{tr(locale,'Mã hóa','Encryption')} <b>{result.environment.encryptionKey.validLength?tr(locale,'Hợp lệ','Valid'):tr(locale,'Không hợp lệ','Invalid')}</b></span></div><code className="ga-callback">Callback: {result.environment.callbackUrl}</code>
      {result.connections.map(connection=>{const issues=connection.api?.issues??[];const state=!connection.success?'failed':issues.length?'partial':'success';return <article className={`ga-diagnostic-connection ${state}`} key={connection.connectionId}><header>{state==='success'?<CheckCircle2 size={17}/>:state==='partial'?<AlertTriangle size={17}/>:<XCircle size={17}/>}<div><strong>{connection.googleEmail}</strong><small>{connection.connectionStatus} · Refresh token: {connection.refreshToken?.stored&&connection.refreshToken.encrypted?tr(locale,'đã mã hóa','encrypted'):''} · Refresh: {connection.refreshToken?.refreshSucceeded?tr(locale,'thành công','success'):tr(locale,'thất bại','failed')}{issues.length?` · ${issues.length} ${tr(locale,'customer cần kiểm tra','customers require attention')}`:''}</small></div></header><dl><div><dt>{tr(locale,'Quyền Developer Token','Developer Token access')}</dt><dd>{accessLabel(connection.developerTokenAccessLevel)}</dd></div><div><dt>{tr(locale,'Dự án Cloud','Cloud project')}</dt><dd>{connection.cloudProject}</dd></div><div><dt>{tr(locale,'Customer có thể truy cập','Accessible customers')}</dt><dd>{connection.api?.accessibleCustomerIds.length?connection.api.accessibleCustomerIds.map(formatCustomerId).join(', '):tr(locale,'Không có','None')}</dd></div></dl>
        {connection.error&&<div className="ga-exact-error"><strong>{tr(locale,'Lỗi Google Ads API','Google Ads API error')}</strong><span>Code: {connection.error.code}</span><span>Type: {connection.error.type}</span><span>Message: {connection.error.message}</span><span>Request ID: {connection.error.requestId||tr(locale,'Không được trả về','Not returned')}</span></div>}
        {issues.length>0&&<section className="ga-diagnostic-issues"><strong>{tr(locale,'Lỗi theo từng tài khoản','Account-level issues')} ({issues.length})</strong><p>{tr(locale,'Các customer dưới đây được bỏ qua; những MCC và tài khoản hợp lệ khác vẫn được xử lý.','These customers are skipped while valid MCCs and accounts continue processing.')}</p><div className="ga-table-wrap"><table className="ga-table"><thead><tr><th>{tr(locale,'Giai đoạn','Phase')}</th><th>Customer ID</th><th>login-customer-id</th><th>Code</th><th>Type</th><th>Message</th><th>Request ID</th></tr></thead><tbody>{issues.map((issue,index)=><tr key={`${issue.phase}-${issue.customerId}-${issue.error.requestId||index}`}><td>{issue.phase}</td><td>{formatCustomerId(issue.customerId)}</td><td>{displayCustomerId(issue.loginCustomerId)}</td><td>{issue.error.code}</td><td>{issue.error.type}</td><td className="ga-diagnostic-message">{issue.error.message}</td><td>{issue.error.requestId||tr(locale,'Không được trả về','Not returned')}</td></tr>)}</tbody></table></div></section>}
        {Boolean(connection.api?.mccs.length||connection.api?.accounts.length)&&<div className="ga-table-wrap"><table className="ga-table"><thead><tr><th>{tr(locale,'Loại','Type')}</th><th>Customer ID</th><th>{tr(locale,'MCC cha','Parent MCC')}</th><th>login-customer-id</th><th>{tr(locale,'Thử nghiệm','Test')}</th></tr></thead><tbody>{connection.api?.mccs.map(item=><tr key={`mcc-${item.customerId}`}><td>{item.manager?`MCC L${item.level}`:tr(locale,'Tài khoản trực tiếp','Direct account')}</td><td>{formatCustomerId(item.customerId)}</td><td>{item.parentCustomerId?formatCustomerId(item.parentCustomerId):tr(locale,'Trực tiếp','Direct')}</td><td>{displayCustomerId(item.loginCustomerId)}</td><td>{item.testAccount?tr(locale,'Có','Yes'):tr(locale,'Không','No')}</td></tr>)}{connection.api?.accounts.map(item=><tr key={`account-${item.parentManagerCustomerId}-${item.customerId}`}><td>{tr(locale,'Tài khoản con','Client')}</td><td>{formatCustomerId(item.customerId)}</td><td>{item.parentCustomerId?formatCustomerId(item.parentManagerCustomerId):tr(locale,'Truy cập trực tiếp','Direct access')}</td><td>{displayCustomerId(item.loginCustomerId)}</td><td>{item.testAccount?tr(locale,'Có','Yes'):tr(locale,'Không','No')}</td></tr>)}</tbody></table></div>}
      </article>})}</div>}
  </section>
}
