'use client';
import {Bug,CheckCircle2,RefreshCw,XCircle} from 'lucide-react';
import {useState} from 'react';
import {formatCustomerId} from '@/lib/google-ads-format';

type DiagnosticError={code:string;type:string;message:string;requestId:string|null;status:number;rootStatus:string|null};
type ConnectionDiagnostic={connectionId:string;googleEmail?:string;connectionStatus?:string;success:boolean;refreshToken?:{stored:boolean;encrypted:boolean;refreshSucceeded?:boolean};developerTokenAccessLevel?:string;cloudProject?:string;api?:{version:string;accessibleCustomerIds:string[];mccs:Array<{customerId:string;parentCustomerId:string|null;manager:boolean;level:number;loginCustomerId:string|null;testAccount:boolean}>;accounts:Array<{customerId:string;parentCustomerId?:string|null;parentManagerCustomerId:string;loginCustomerId:string|null;testAccount:boolean}>};error?:DiagnosticError};
type DiagnosticPayload={data?:{checkedAt:string;environment:{configured:boolean;missing:string[];oauthClientId:{configured:boolean;length:number;suffix:string|null};oauthClientSecret:{configured:boolean;length:number};developerToken:{configured:boolean;length:number;fingerprint:string|null;expectedLength:number};encryptionKey:{configured:boolean;validLength:boolean};callbackUrl:string;apiVersion:string};connections:ConnectionDiagnostic[]};error?:{message?:string}};

function accessLabel(value:string|undefined){if(value==='TEST')return'Token chỉ dùng được với test accounts, không thể truy cập production Google Ads.';if(value==='NOT_EXPOSED_BY_API')return'Google Ads API không công bố chính xác Explorer/Basic/Standard; kiểm tra trong API Center.';return value||'Chưa xác định'}
function displayCustomerId(value:string|null|undefined){return value?formatCustomerId(value):'Omitted (direct access)'}

export function DiagnosticsPanel(){
  const[busy,setBusy]=useState(false);const[result,setResult]=useState<DiagnosticPayload['data']>();const[error,setError]=useState('');
  async function run(){setBusy(true);setError('');const response=await fetch('/api/google-ads/diagnostics',{method:'POST'});const payload=await response.json() as DiagnosticPayload;setBusy(false);if(!response.ok||!payload.data){setError(payload.error?.message||'Không thể chạy diagnostics.');return}setResult(payload.data)}
  return <section className="ga-diagnostics ga-panel"><div className="ga-panel-head"><div><h2>Google Ads diagnostics</h2><p>Kiểm tra OAuth refresh, cấu hình backend, accessible customers, MCC hierarchy và lỗi API nguyên bản. Không hiển thị token/secret.</p></div><button className="ga-secondary" disabled={busy} onClick={()=>void run()}>{busy?<RefreshCw className="spin" size={14}/>:<Bug size={14}/>} {busy?'Đang kiểm tra...':'Run diagnostics'}</button></div>
    {error&&<div className="ga-diagnostic-error"><XCircle size={17}/>{error}</div>}
    {result&&<div className="ga-diagnostic-body"><div className="ga-diagnostic-config"><span>API <b>{result.environment.apiVersion}</b></span><span>Client ID <b>{result.environment.oauthClientId.configured?'Configured':'Missing'}</b></span><span>Client Secret <b>{result.environment.oauthClientSecret.configured?'Configured':'Missing'}</b></span><span>Developer Token <b>{result.environment.developerToken.length}/{result.environment.developerToken.expectedLength} chars</b></span><span>Encryption <b>{result.environment.encryptionKey.validLength?'Valid':'Invalid'}</b></span></div><code className="ga-callback">Callback: {result.environment.callbackUrl}</code>
      {result.connections.map(connection=><article className="ga-diagnostic-connection" key={connection.connectionId}><header>{connection.success?<CheckCircle2 size={17}/>:<XCircle size={17}/>}<div><strong>{connection.googleEmail}</strong><small>{connection.connectionStatus} · Refresh token: {connection.refreshToken?.stored&&connection.refreshToken.encrypted?'encrypted':''} · Refresh: {connection.refreshToken?.refreshSucceeded?'success':'failed'}</small></div></header><dl><div><dt>Developer Token access</dt><dd>{accessLabel(connection.developerTokenAccessLevel)}</dd></div><div><dt>Cloud project</dt><dd>{connection.cloudProject}</dd></div><div><dt>Accessible customers</dt><dd>{connection.api?.accessibleCustomerIds.length?connection.api.accessibleCustomerIds.map(formatCustomerId).join(', '):'None'}</dd></div></dl>
        {connection.error&&<div className="ga-exact-error"><strong>Google Ads API error</strong><span>Code: {connection.error.code}</span><span>Type: {connection.error.type}</span><span>Message: {connection.error.message}</span><span>Request ID: {connection.error.requestId||'Not returned'}</span></div>}
        {Boolean(connection.api?.mccs.length||connection.api?.accounts.length)&&<div className="ga-table-wrap"><table className="ga-table"><thead><tr><th>Type</th><th>Customer ID</th><th>Parent MCC</th><th>login-customer-id</th><th>Test</th></tr></thead><tbody>{connection.api?.mccs.map(item=><tr key={`mcc-${item.customerId}`}><td>{item.manager?`MCC L${item.level}`:'Direct account'}</td><td>{formatCustomerId(item.customerId)}</td><td>{item.parentCustomerId?formatCustomerId(item.parentCustomerId):'Direct'}</td><td>{displayCustomerId(item.loginCustomerId)}</td><td>{item.testAccount?'Yes':'No'}</td></tr>)}{connection.api?.accounts.map(item=><tr key={`account-${item.parentManagerCustomerId}-${item.customerId}`}><td>Client</td><td>{formatCustomerId(item.customerId)}</td><td>{item.parentCustomerId?formatCustomerId(item.parentManagerCustomerId):'Direct access'}</td><td>{displayCustomerId(item.loginCustomerId)}</td><td>{item.testAccount?'Yes':'No'}</td></tr>)}</tbody></table></div>}
      </article>)}</div>}
  </section>
}
