import { AlertTriangle,CheckCircle2,Link2,Plus } from 'lucide-react';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { googleAdsConfigStatus } from '@/services/google-ads';
import { ConnectionActions } from './connection-actions';
import {DiagnosticsPanel} from './diagnostics-panel';
import { dateLocale,tr,type AppLocale } from '@/lib/i18n';
import { getAppLocale } from '@/lib/i18n-server';

const errorMessages=(locale:AppLocale):Record<string,string>=>({OAUTH_CANCELLED:tr(locale,'Bạn đã hủy đăng nhập Google.','Google sign-in was cancelled.'),OAUTH_FAILED:tr(locale,'Google OAuth không thể hoàn tất.','Google OAuth could not be completed.'),OAUTH_STATE_INVALID:tr(locale,'Phiên OAuth không hợp lệ hoặc đã hết hạn.','The OAuth session is invalid or expired.'),OAUTH_EXCHANGE_FAILED:tr(locale,'Không thể đổi mã OAuth.','The OAuth authorization code could not be exchanged.'),REFRESH_TOKEN_MISSING:tr(locale,'Google không trả refresh token. Hãy thu hồi quyền ứng dụng và thử lại.','Google did not return a refresh token. Revoke the application access and try again.'),PERMISSION_DENIED:tr(locale,'Tài khoản Google không có quyền Google Ads cần thiết.','The Google account lacks the required Google Ads permissions.'),GOOGLE_CONNECTION_FAILED:tr(locale,'Không thể đồng bộ Google Ads.','Google Ads could not be synchronized.')});
function readableConnectionError(value:string,locale:AppLocale){return value.includes('DEVELOPER_TOKEN_NOT_APPROVED')?tr(locale,'Developer Token đang ở mức Test; kết nối OAuth vẫn hoạt động nhưng chưa thể đọc tài khoản production.','The Developer Token has Test access; OAuth works, but production accounts cannot be read.'):value}

export default async function ConnectionsPage({searchParams}:{searchParams:Promise<{connected?:string;error?:string;errorType?:string;errorMessage?:string;requestId?:string;mcc?:string;accounts?:string}>}){
  const user=await getCurrentUser();if(!user)redirect('/login?returnTo=/google-ads');const query=await searchParams;const locale=await getAppLocale();
  const config=googleAdsConfigStatus();
  const connections=await prisma.googleConnection.findMany({where:user.role==='ADMIN'?{userId:user.id}:{mccs:{some:{userPermissions:{some:{userId:user.id}}}}},include:{mccs:{where:user.role==='ADMIN'?{}:{userPermissions:{some:{userId:user.id}}},select:{manager:true,_count:{select:{accounts:true}}}}},orderBy:{createdAt:'desc'}});
  return <><div className="ga-page-head"><div><p>GOOGLE ADS</p><h1>{tr(locale,'Kết nối','Connections')}</h1><span>{tr(locale,'Kết nối Gmail thực tế bằng OAuth; không nhập mật khẩu Google vào website.','Connect a real Gmail account with OAuth; never enter a Google password on this website.')}</span></div>{user.role==='ADMIN'&&config.configured&&<a className="ga-primary" href="/api/auth/google-ads"><Plus size={15}/>{tr(locale,'Đăng nhập Google Ads','Sign in to Google Ads')}</a>}</div>
    {query.connected==='1'&&<div className="ga-alert success"><CheckCircle2 size={19}/><div><strong>{tr(locale,'Kết nối thành công','Connection successful')}</strong><p>{tr(locale,`Đã đồng bộ ${query.mcc||0} MCC và ${query.accounts||0} tài khoản quảng cáo.`,`Synchronized ${query.mcc||0} MCCs and ${query.accounts||0} advertising accounts.`)}</p></div></div>}
    {query.error&&<div className="ga-alert danger"><AlertTriangle size={19}/><div><strong>{tr(locale,'Kết nối chưa hoàn tất','Connection incomplete')}</strong><p>{query.errorMessage||errorMessages(locale)[query.error]||`${tr(locale,'Lỗi','Error')}: ${query.error}`}</p>{query.errorType&&<code>{`Code: ${query.error}\nType: ${query.errorType}\nRequest ID: ${query.requestId||'Not returned'}`}</code>}</div></div>}
    {!config.configured&&<section className="ga-config"><AlertTriangle size={22}/><div><h2>{tr(locale,'Cần cấu hình Google OAuth','Google OAuth configuration required')}</h2><p>{tr(locale,'Thêm các biến backend sau trong Vercel, không dùng tiền tố NEXT_PUBLIC:','Add the following backend variables in Vercel without the NEXT_PUBLIC prefix:')}</p><code>{config.missing.join('\n')}</code><small>Redirect URI: {(process.env.NEXTAUTH_URL||'https://your-domain.com')}/api/auth/google-ads/callback</small></div></section>}
    {connections.length===0?<section className="ga-empty"><Link2 size={28}/><h2>{tr(locale,'Kết nối tài khoản Google Ads','Connect a Google Ads account')}</h2><p>{tr(locale,'Đăng nhập bằng Gmail có quyền truy cập MCC hoặc tài khoản Google Ads.','Sign in with a Gmail account that can access an MCC or Google Ads account.')}</p>{user.role==='ADMIN'&&config.configured&&<a className="ga-primary" href="/api/auth/google-ads">{tr(locale,'Đăng nhập Google Ads','Sign in to Google Ads')}</a>}</section>:<div className="ga-connection-list">{connections.map(connection=>{const mccCount=connection.mccs.filter(item=>item.manager).length;const accountCount=connection.mccs.reduce((sum,item)=>sum+item._count.accounts,0);return <article className="ga-connection" key={connection.id}><div className="ga-connection-icon"><Link2 size={19}/></div><div className="ga-connection-info"><div><h2>{connection.googleEmail}</h2><span className={`ga-status ${connection.status.toLowerCase()}`}>{connection.status==='CONNECTED'?tr(locale,'● Đã kết nối','● Connected'):connection.status==='REAUTH_REQUIRED'?tr(locale,'Cần đăng nhập lại','Reconnect required'):tr(locale,'Đã ngắt kết nối','Disconnected')}</span></div><p>{mccCount} MCC · {accountCount} {tr(locale,'tài khoản','accounts')}</p><small>{tr(locale,'Đồng bộ','Synchronized')}: {connection.lastSyncAt?connection.lastSyncAt.toLocaleString(dateLocale(locale)):tr(locale,'Chưa đồng bộ','Not synchronized')}</small>{connection.lastError&&<div className="ga-connection-warning"><AlertTriangle size={14}/><span>{readableConnectionError(connection.lastError,locale)}</span></div>}</div>{user.role==='ADMIN'&&<ConnectionActions id={connection.id} status={connection.status}/>}</article>})}</div>}
    {user.role==='ADMIN'&&connections.length>0&&<DiagnosticsPanel/>}
  </>
}
