import { Zap } from 'lucide-react';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { allowedMccIds } from '@/lib/data-access';
import { formatCustomerId,formatMoney } from '@/lib/google-ads-format';
import { prisma } from '@/lib/prisma';
import { CampaignActions } from '../campaign-actions';

export default async function CampaignsPage(){const user=await getCurrentUser();if(!user)redirect('/login?returnTo=/google-ads/campaigns');const allowed=await allowedMccIds(user);const campaigns=await prisma.campaign.findMany({where:{customerAccount:{mcc:allowed===null?{}:{id:{in:allowed}}}},include:{customerAccount:{include:{mcc:true}}},orderBy:{updatedAt:'desc'},take:1000});return <><div className="ga-page-head"><div><p>GOOGLE ADS</p><h1>Campaigns</h1><span>ADMIN có thể Pause, Enable, Update Budget; STAFF chỉ đọc.</span></div></div>{campaigns.length===0?<section className="ga-empty"><Zap size={28}/><h2>Chưa đồng bộ campaigns</h2><p>Mở một account để hệ thống đọc campaign và metrics thực tế từ Google Ads API.</p></section>:<section className="ga-panel ga-table-panel"><div className="ga-table-wrap"><table className="ga-table"><thead><tr><th>Campaign</th><th>Account</th><th>MCC</th><th>Status</th><th>Budget</th><th>Actions</th></tr></thead><tbody>{campaigns.map(campaign=><tr key={campaign.id}><td><strong>{campaign.name}</strong><small>ID {campaign.campaignId}</small></td><td><a href={`/google-ads/accounts/${campaign.customerAccount.id}`}>{campaign.customerAccount.name}</a><small>{formatCustomerId(campaign.customerAccount.customerId)}</small></td><td>{campaign.customerAccount.mcc.name}</td><td><span className={`ga-status ${campaign.status==='ENABLED'?'connected':'reauth_required'}`}>{campaign.status}</span></td><td>{formatMoney(Number(campaign.budget),campaign.customerAccount.currency||'VND')}</td><td>{user.role==='ADMIN'?<CampaignActions id={campaign.id} status={campaign.status} budget={Number(campaign.budget)}/>:<span className="ga-readonly">Read only</span>}</td></tr>)}</tbody></table></div></section>}</>}
