import { Zap } from 'lucide-react';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { allowedMccIds } from '@/lib/data-access';
import { formatCustomerId,formatMoney } from '@/lib/google-ads-format';
import { prisma } from '@/lib/prisma';
import { CampaignActions } from '../campaign-actions';
import { dateLocale,tr } from '@/lib/i18n';
import { getAppLocale } from '@/lib/i18n-server';

export default async function CampaignsPage(){const user=await getCurrentUser();if(!user)redirect('/login?returnTo=/google-ads/campaigns');const locale=await getAppLocale();const numberLocale=dateLocale(locale);const allowed=await allowedMccIds(user);const campaigns=await prisma.campaign.findMany({where:{customerAccount:{mcc:allowed===null?{}:{id:{in:allowed}}}},include:{customerAccount:{include:{mcc:true}}},orderBy:{updatedAt:'desc'},take:1000});return <><div className="ga-page-head"><div><p>GOOGLE ADS</p><h1>{tr(locale,'Chiến dịch','Campaigns')}</h1><span>{tr(locale,'ADMIN có thể tạm dừng, bật và cập nhật ngân sách; STAFF chỉ đọc.','ADMIN can pause, enable, and update budgets; STAFF is read-only.')}</span></div></div>{campaigns.length===0?<section className="ga-empty"><Zap size={28}/><h2>{tr(locale,'Chưa đồng bộ chiến dịch','No campaigns synchronized')}</h2><p>{tr(locale,'Mở một tài khoản để hệ thống đọc chiến dịch và chỉ số thực tế từ Google Ads API.','Open an account so the system can load real campaigns and metrics from the Google Ads API.')}</p></section>:<section className="ga-panel ga-table-panel"><div className="ga-table-wrap"><table className="ga-table"><thead><tr><th>{tr(locale,'Chiến dịch','Campaign')}</th><th>{tr(locale,'Tài khoản','Account')}</th><th>MCC</th><th>{tr(locale,'Trạng thái','Status')}</th><th>{tr(locale,'Ngân sách','Budget')}</th><th>{tr(locale,'Thao tác','Actions')}</th></tr></thead><tbody>{campaigns.map(campaign=><tr key={campaign.id}><td><strong>{campaign.name}</strong><small>ID {campaign.campaignId}</small></td><td><a href={`/google-ads/accounts/${campaign.customerAccount.id}`}>{campaign.customerAccount.name}</a><small>{formatCustomerId(campaign.customerAccount.customerId)}</small></td><td>{campaign.customerAccount.mcc.name}</td><td><span className={`ga-status ${campaign.status==='ENABLED'?'connected':'reauth_required'}`}>{campaign.status}</span></td><td>{formatMoney(Number(campaign.budget),campaign.customerAccount.currency||'VND',numberLocale)}</td><td>{user.role==='ADMIN'?<CampaignActions id={campaign.id} status={campaign.status} budget={Number(campaign.budget)}/>:<span className="ga-readonly">{tr(locale,'Chỉ đọc','Read only')}</span>}</td></tr>)}</tbody></table></div></section>}</>}
